"""
Django settings for wen project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import pymysql
pymysql.install_as_MySQLdb()
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd$3+be3*jo^%bu*-w=z^1d%b%95syv#_eq0kq_8hhc59wk!t9('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'people',
    'sites',
    'question',
    'page',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.utils.deprecation.MiddlewareMixin',
    'people.views.MyMiddleware',
]

ROOT_URLCONF = 'wen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wen.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default':
    {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wenwen',
        'USER': 'root',
        'PASSWORD': 'dfg159dfg',
        'HOST': '139.199.10.183',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static'),]



AUTH_USER_MODEL = 'people.Member'

#主题分页每页的行数
NUM_TOPIC_PER_PAGE = 10
#每个帖子里每页显示的评论数
NUM_COMMENT_PER_PAGE = 10
#消息通知页面每页显示数量
NUM_NOTICE_PER_PAGE = 5

#gravatar的参数设置
GRAVATAR_URL_PREFIX = 'http://www.gravatar.com/'
GRAVATAR_DEFAULT_IMAGE = ''
GRAVATAR_DEFAULT_RATING = 'g'
GRAVATAR_DEFAULT_SIZE = 48

SITE_URL = 'http://www.trickster.xyz'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_USE_TLS = True

EMAIL_TOKEN_SALT = 'TSFH'

EMAIL_HOST_USER = '714379433@qq.com'
EMAIL_HOST_PASSWORD = 'fsxsofwgocrrbcja'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
LOGIN_URL = '/login'

qiniu_AK = 'w0J6gz-V5s18F9ce3P-rd4GISMhNYO9-VXwReJ2K'
qiniu_SK = 'I3kNonNrWNCb3OAdrt-GTWobWwxtjLbDvNP4c8aD'