# Generated by Django 2.1 on 2018-08-07 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类别名称')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('author', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritedTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('slug', models.SlugField(max_length=100, verbose_name='url标识符')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('num_topics', models.IntegerField(default=0, verbose_name='主题数')),
                ('category', models.ForeignKey(on_delete=True, to='question.Category', verbose_name='所属类别')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='来自用户')),
                ('to_user', models.ForeignKey(on_delete=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('num_views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('num_comments', models.IntegerField(default=0, verbose_name='评论数')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('last_reply', models.ForeignKey(on_delete=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后回复者')),
                ('node', models.ForeignKey(on_delete=True, to='question.Node', verbose_name='所属节点')),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=True, to='question.Topic', verbose_name='主题'),
        ),
        migrations.AddField(
            model_name='favoritedtopic',
            name='topic',
            field=models.ForeignKey(on_delete=True, to='question.Topic', verbose_name='主题'),
        ),
        migrations.AddField(
            model_name='favoritedtopic',
            name='user',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=True, to='question.Topic', verbose_name='所属主题'),
        ),
    ]
